targets:
  $default:
    builders:
      freezed:
        enabled: true
      injectable_generator|injectable_builder:
        enabled: true
      injectable_generator|injectable_config_builder:
        enabled: true
      flutter_gen_runner:
        enabled: true
