name: app_host
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  dependency:
    path: ../dependency

  # Modules
  auth_module:
    path: ../auth_module
  home_module:
    path: ../home_module
  common_ui:
    path: ../common_ui
  app_route:
    path: ../app_route
  app_networking:
    path: ../app_networking

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  dev_dependency:
    path: ../dev_dependency

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
