name: home_module
description: Home module - dashboard with bottom navigation and user profile
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter
  dependency:
    path: ../dependency
  common_ui:
    path: ../common_ui
  auth_module:
    path: ../auth_module
  app_route:
    path: ../app_route

dev_dependencies:
  build_runner: ^2.12.2
  flutter_lints: ^6.0.0
  dev_dependency:
    path: ../dev_dependency
  test_dependency:
    path: ../test_dependency

flutter:
  uses-material-design: true
