name: common_ui
description: Shared UI components, theme, assets and fonts for the monorepo
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter
  dependency:
    path: ../dependency

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  dev_dependency:
    path: ../dev_dependency

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/gen/
  line_length: 100
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets
