import 'package:flutter/widgets.dart';
import '../l10n/app_localizations.dart';

/// A class that provides access to localized strings without [BuildContext].
/// Similar to the `S` class generated by the `flutter_intl` plugin.
class AppLocalizations {
  static GeneratedAppLocalizations? _current;

  /// Returns the current instance of [GeneratedAppLocalizations].
  ///
  /// Note: [AppLocalizations.load] must be called at least once (e.g., during app startup
  /// or whenever the locale changes) before accessing this property.
  static GeneratedAppLocalizations get current {
    assert(
      _current != null,
      'No instance of GeneratedAppLocalizations was loaded. '
      'Did you forget to call AppLocalizations.load(locale)?',
    );
    return _current!;
  }

  /// Manually loads and sets the current [GeneratedAppLocalizations] for a given [locale].
  /// Use this to initialize localization or update it when the app's locale changes.
  static GeneratedAppLocalizations load(Locale locale) {
    final instance = lookupGeneratedAppLocalizations(locale);
    _current = instance;
    return instance;
  }

  /// Proxies to [GeneratedAppLocalizations.of].
  static GeneratedAppLocalizations of(BuildContext context) {
    return GeneratedAppLocalizations.of(context);
  }

  /// Proxies to [GeneratedAppLocalizations.delegate].
  static LocalizationsDelegate<GeneratedAppLocalizations> get delegate =>
      GeneratedAppLocalizations.delegate;

  /// Proxies to [GeneratedAppLocalizations.localizationsDelegates].
  static List<LocalizationsDelegate<dynamic>> get localizationsDelegates =>
      GeneratedAppLocalizations.localizationsDelegates;

  /// Proxies to [GeneratedAppLocalizations.supportedLocales].
  static List<Locale> get supportedLocales =>
      GeneratedAppLocalizations.supportedLocales;
}
